version: '3.8'

networks:
  backend:
    driver: bridge

services:
  hash:
    image: ko.local/github.com/0x5d/hash
    container_name: hash
    environment:
      DB_URL: postgresql://hash:hash@postgres:5432/postgres
      CACHE_ADDR: "redis:6379"
      HTTP_ADV_ADDR: "http://localhost:8080"
      DB_ID_TABLE_ID: 1
      DB_MIGRATIONS_TABLE: "migrations"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - backend

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: hash
      POSTGRES_PASSWORD: hash
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
